package com.yxjz.hrxm.domestic.user.mapper;

import com.yxjz.hrxm.domestic.user.pojo.Nanny;
import com.yxjz.hrxm.domestic.user.pojo.NannyExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface NannyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nanny
     *
     * @mbggenerated Fri Feb 19 09:05:23 CST 2021
     */
    int countByExample(NannyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nanny
     *
     * @mbggenerated Fri Feb 19 09:05:23 CST 2021
     */
    int deleteByExample(NannyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nanny
     *
     * @mbggenerated Fri Feb 19 09:05:23 CST 2021
     */
    int deleteByPrimaryKey(Integer nId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nanny
     *
     * @mbggenerated Fri Feb 19 09:05:23 CST 2021
     */
    int insert(Nanny record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nanny
     *
     * @mbggenerated Fri Feb 19 09:05:23 CST 2021
     */
    int insertSelective(Nanny record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nanny
     *
     * @mbggenerated Fri Feb 19 09:05:23 CST 2021
     */
    List<Nanny> selectByExample(NannyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nanny
     *
     * @mbggenerated Fri Feb 19 09:05:23 CST 2021
     */
    Nanny selectByPrimaryKey(Integer nId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nanny
     *
     * @mbggenerated Fri Feb 19 09:05:23 CST 2021
     */
    int updateByExampleSelective(@Param("record") Nanny record, @Param("example") NannyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nanny
     *
     * @mbggenerated Fri Feb 19 09:05:23 CST 2021
     */
    int updateByExample(@Param("record") Nanny record, @Param("example") NannyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nanny
     *
     * @mbggenerated Fri Feb 19 09:05:23 CST 2021
     */
    int updateByPrimaryKeySelective(Nanny record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nanny
     *
     * @mbggenerated Fri Feb 19 09:05:23 CST 2021
     */
    int updateByPrimaryKey(Nanny record);
}