package com.yxjz.hrxm.domestic.user.pojo;

public class DUserRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_user_role.userid
     *
     * @mbggenerated Tue Feb 23 17:57:19 CST 2021
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_user_role.roleid
     *
     * @mbggenerated Tue Feb 23 17:57:19 CST 2021
     */
    private Integer roleid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_user_role.userid
     *
     * @return the value of d_user_role.userid
     *
     * @mbggenerated Tue Feb 23 17:57:19 CST 2021
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_user_role.userid
     *
     * @param userid the value for d_user_role.userid
     *
     * @mbggenerated Tue Feb 23 17:57:19 CST 2021
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_user_role.roleid
     *
     * @return the value of d_user_role.roleid
     *
     * @mbggenerated Tue Feb 23 17:57:19 CST 2021
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_user_role.roleid
     *
     * @param roleid the value for d_user_role.roleid
     *
     * @mbggenerated Tue Feb 23 17:57:19 CST 2021
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }
}