package com.yxjz.hrxm.domestic.user.pojo;

public class Nanny {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nanny.n_id
     *
     * @mbggenerated Fri Feb 19 09:05:23 CST 2021
     */
    private Integer nId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nanny.n_name
     *
     * @mbggenerated Fri Feb 19 09:05:23 CST 2021
     */
    private String nName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nanny.n_age
     *
     * @mbggenerated Fri Feb 19 09:05:23 CST 2021
     */
    private Integer nAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nanny.n_tel
     *
     * @mbggenerated Fri Feb 19 09:05:23 CST 2021
     */
    private String nTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nanny.n_contract_id
     *
     * @mbggenerated Fri Feb 19 09:05:23 CST 2021
     */
    private Integer nContractId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nanny.order_id
     *
     * @mbggenerated Fri Feb 19 09:05:23 CST 2021
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nanny.status
     *
     * @mbggenerated Fri Feb 19 09:05:23 CST 2021
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nanny.n_id
     *
     * @return the value of nanny.n_id
     *
     * @mbggenerated Fri Feb 19 09:05:23 CST 2021
     */
    public Integer getnId() {
        return nId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nanny.n_id
     *
     * @param nId the value for nanny.n_id
     *
     * @mbggenerated Fri Feb 19 09:05:23 CST 2021
     */
    public void setnId(Integer nId) {
        this.nId = nId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nanny.n_name
     *
     * @return the value of nanny.n_name
     *
     * @mbggenerated Fri Feb 19 09:05:23 CST 2021
     */
    public String getnName() {
        return nName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nanny.n_name
     *
     * @param nName the value for nanny.n_name
     *
     * @mbggenerated Fri Feb 19 09:05:23 CST 2021
     */
    public void setnName(String nName) {
        this.nName = nName == null ? null : nName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nanny.n_age
     *
     * @return the value of nanny.n_age
     *
     * @mbggenerated Fri Feb 19 09:05:23 CST 2021
     */
    public Integer getnAge() {
        return nAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nanny.n_age
     *
     * @param nAge the value for nanny.n_age
     *
     * @mbggenerated Fri Feb 19 09:05:23 CST 2021
     */
    public void setnAge(Integer nAge) {
        this.nAge = nAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nanny.n_tel
     *
     * @return the value of nanny.n_tel
     *
     * @mbggenerated Fri Feb 19 09:05:23 CST 2021
     */
    public String getnTel() {
        return nTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nanny.n_tel
     *
     * @param nTel the value for nanny.n_tel
     *
     * @mbggenerated Fri Feb 19 09:05:23 CST 2021
     */
    public void setnTel(String nTel) {
        this.nTel = nTel == null ? null : nTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nanny.n_contract_id
     *
     * @return the value of nanny.n_contract_id
     *
     * @mbggenerated Fri Feb 19 09:05:23 CST 2021
     */
    public Integer getnContractId() {
        return nContractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nanny.n_contract_id
     *
     * @param nContractId the value for nanny.n_contract_id
     *
     * @mbggenerated Fri Feb 19 09:05:23 CST 2021
     */
    public void setnContractId(Integer nContractId) {
        this.nContractId = nContractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nanny.order_id
     *
     * @return the value of nanny.order_id
     *
     * @mbggenerated Fri Feb 19 09:05:23 CST 2021
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nanny.order_id
     *
     * @param orderId the value for nanny.order_id
     *
     * @mbggenerated Fri Feb 19 09:05:23 CST 2021
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nanny.status
     *
     * @return the value of nanny.status
     *
     * @mbggenerated Fri Feb 19 09:05:23 CST 2021
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nanny.status
     *
     * @param status the value for nanny.status
     *
     * @mbggenerated Fri Feb 19 09:05:23 CST 2021
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}