package com.yxjz.hrxm.domestic.user.pojo;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userid
     *
     * @mbggenerated Tue Mar 09 17:55:22 CST 2021
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.username
     *
     * @mbggenerated Tue Mar 09 17:55:22 CST 2021
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.passworld
     *
     * @mbggenerated Tue Mar 09 17:55:22 CST 2021
     */
    private String passworld;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.permid
     *
     * @mbggenerated Tue Mar 09 17:55:22 CST 2021
     */
    private Integer permid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.alias
     *
     * @mbggenerated Tue Mar 09 17:55:22 CST 2021
     */
    private String alias;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.roleid
     *
     * @mbggenerated Tue Mar 09 17:55:22 CST 2021
     */
    private String roleid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userid
     *
     * @return the value of user.userid
     *
     * @mbggenerated Tue Mar 09 17:55:22 CST 2021
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userid
     *
     * @param userid the value for user.userid
     *
     * @mbggenerated Tue Mar 09 17:55:22 CST 2021
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.username
     *
     * @return the value of user.username
     *
     * @mbggenerated Tue Mar 09 17:55:22 CST 2021
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.username
     *
     * @param username the value for user.username
     *
     * @mbggenerated Tue Mar 09 17:55:22 CST 2021
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.passworld
     *
     * @return the value of user.passworld
     *
     * @mbggenerated Tue Mar 09 17:55:22 CST 2021
     */
    public String getPassworld() {
        return passworld;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.passworld
     *
     * @param passworld the value for user.passworld
     *
     * @mbggenerated Tue Mar 09 17:55:22 CST 2021
     */
    public void setPassworld(String passworld) {
        this.passworld = passworld == null ? null : passworld.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.permid
     *
     * @return the value of user.permid
     *
     * @mbggenerated Tue Mar 09 17:55:22 CST 2021
     */
    public Integer getPermid() {
        return permid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.permid
     *
     * @param permid the value for user.permid
     *
     * @mbggenerated Tue Mar 09 17:55:22 CST 2021
     */
    public void setPermid(Integer permid) {
        this.permid = permid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.alias
     *
     * @return the value of user.alias
     *
     * @mbggenerated Tue Mar 09 17:55:22 CST 2021
     */
    public String getAlias() {
        return alias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.alias
     *
     * @param alias the value for user.alias
     *
     * @mbggenerated Tue Mar 09 17:55:22 CST 2021
     */
    public void setAlias(String alias) {
        this.alias = alias == null ? null : alias.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.roleid
     *
     * @return the value of user.roleid
     *
     * @mbggenerated Tue Mar 09 17:55:22 CST 2021
     */
    public String getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.roleid
     *
     * @param roleid the value for user.roleid
     *
     * @mbggenerated Tue Mar 09 17:55:22 CST 2021
     */
    public void setRoleid(String roleid) {
        this.roleid = roleid == null ? null : roleid.trim();
    }
}